name: New Workflow (action)
on: workflow_dispatch

jobs:
  verify-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get source code
        uses: actions/checkout@v5.0.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v5.0.0
        with:
          node-version: 20
      - run: |
          npm install --force
          npm run prettier
          npm run lint
